
// 运维平台
export let arr = [
    {
        img:require('@/assets/1.png'),
        href:'https://cn.vuejs.org/',
        content:'Vue官网'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://reactjs.bootcss.com/',
        content:'React官网'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://element.eleme.cn/#/zh-CN/component/layout',
        content:'Element官网'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://github.com/',
        content:'Github官网'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://github.com/doocs',
        content:'Github中文文档'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://lanhuapp.com/',
        content:'蓝湖'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://cloud.tencent.com/developer/doc/1270',
        content:'腾讯云学习平台'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://www.bilibili.com/',
        content:'B站'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://juejin.cn/frontend',
        content:'掘金'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://www.zhihu.com/',
        content:'知乎'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://pc.qq.com/detail/8/detail_22868.html',
        content:'下载'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://www.iconfont.cn/',
        content:'阿里图库Iconfont'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://fanyi.youdao.com/?keyfrom=fanyi-new.logo',
        content:'有道云在线翻译'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://time.geekbang.org/',
        content:'极客时间'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://tool.chinaz.com/dns/?type=1&host=github.com&ip=',
        content:'dns查询'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'http://172.16.68.236/profile/preferences',
        content:'gitlab代码托管平台'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'http://172.16.81.22:3000/group/11',
        content:'yapi接口托管平台'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'http://jenkins.hdfax.com/view/test_%E5%9F%BA%E9%87%91/job/tfun-jhjzfund-%E9%87%91%E6%B5%B7%E4%B9%9D%E5%B7%9E%E5%9F%BA%E9%87%91%E5%AE%98%E7%BD%91%E7%B3%BB%E7%BB%9F/job/tfun-jhjzfund-oms-website-pc/',
        content:'Jenkins部署平台'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://www.tapd.cn/my_dashboard',
        content:'Tapd流程控制平台'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://pages.github.com/',
        content:'GitHub静态网站搭建'
    },
    {
        img:require('@/assets/2.jpg'),
        href:'https://greasyfork.org/zh-CN/scripts',
        content:'脚本'
    },
]
// 应用平台
export let brr = [
    {
        img:require('@/assets/5.png'),
        href:'https://www.zhipin.com/web/geek/resume?ka=header-resume',
        content:'Boss直聘'
    },
    
]